name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3
        with:
          path: derived-imgs
      - name: Checkout Raw Imgs
        uses: actions/checkout@v3
        with:
          repository: buddhist-uni/imgs
          path: imgs
      - name: Checkout Big Imgs
        uses: actions/checkout@v3
        with:
          repository: buddhist-uni/original_size_imgs
          path: original_size_imgs
      - name: Generate Image Variants
        run: |
            convert --version
            bash ./derived-imgs/gen_image_variants.bash
      - name: Upload Build as Artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: output
          retention-days: 62
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy the Artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

